// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNnF-2-rvaTYY6DaMSZVes6Cv4t33X3aw',
    appId: '1:442653183551:web:01d45072e6231f8316728a',
    messagingSenderId: '442653183551',
    projectId: 'mobileapps-g45-tutoriauniandes',
    authDomain: 'mobileapps-g45-tutoriauniandes.firebaseapp.com',
    storageBucket: 'mobileapps-g45-tutoriauniandes.firebasestorage.app',
    measurementId: 'G-0YQ2H726HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD16FnzXBgDUzTOi0Xeh0UveuKepdS2vBw',
    appId: '1:442653183551:android:895e5f9695ffe01116728a',
    messagingSenderId: '442653183551',
    projectId: 'mobileapps-g45-tutoriauniandes',
    storageBucket: 'mobileapps-g45-tutoriauniandes.firebasestorage.app',
  );
}
